# Crypto Agent Profile with Task-Aware Agent Mapping
# Optimized executor configurations for different task types:
# - RETRIEVE: Fast data fetching (Gemini Flash)
# - CODE_INTERPRET: Complex analysis (Claude Sonnet 4.5 + E2B)
# - THINK: Deep reasoning (Claude Sonnet 4.5)
# - WRITE: Professional reports (Claude Sonnet 4.5)

# Default agent configurations (used for Atomizer, Planner, Aggregator, Verifier)
agents:
  # Atomizer: Fast decision-making with Gemini Flash
  atomizer:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 1000

  # Planner: Strategic planning with Gemini Flash
  planner:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.1
      max_tokens: 4000
    agent_config:
      max_subtasks: 12

  # Default Executor (fallback for unmapped task types)
  executor:
    llm:
      model: openrouter/anthropic/claude-sonnet-4.5
      temperature: 0.2
      max_tokens: 16000
    prediction_strategy: react
    agent_config:
      max_executions: 10

    # Default toolkits (all available)
    # NOTE: Configs are homogenized across all task types for maximum cache reuse
    toolkits:
      - class_name: E2BToolkit
        enabled: true
        toolkit_config:
          timeout: 600
          max_lifetime_hours: 23.5
          auto_reinitialize: true

      - class_name: SerperToolkit
        enabled: true
        # HOMOGENIZED: Standard comprehensive tool set
        include_tools:
          - search
          - search_news
          - search_scholar
        toolkit_config:
          location: us
          language: en
          num_results: 5  # Standard across all agents

      - class_name: ArkhamToolkit
        enabled: true
        # HOMOGENIZED: Same comprehensive tool set as all task types
        include_tools:
          - get_top_tokens
          - get_supported_chains
        toolkit_config:
          enable_analysis: true  # Standard: always enabled

      - class_name: DefiLlamaToolkit
        enabled: true
        # HOMOGENIZED: Same comprehensive tool set as all task types
        include_tools:
          - get_protocols
          - get_protocol_tvl
          - get_chains
          - get_protocol_detail
          - get_chain_historical_tvl
          - get_protocol_fees
        toolkit_config:
          enable_analysis: true  # Standard: always enabled
          enable_pro_features: true

      - class_name: CoinGeckoToolkit
        enabled: true
        # HOMOGENIZED: Same comprehensive tool set as all task types
        include_tools:
          - get_coin_price
          - get_coin_info
          - get_coins_markets
          - get_global_crypto_data
          - get_token_price_by_contract
          - search_coins_exchanges_categories
          - get_coin_market_chart
          - get_coin_ohlc
        toolkit_config:
          enable_analysis: true  # Standard: always enabled
          use_pro: true

      - class_name: BinanceToolkit
        enabled: true
        # HOMOGENIZED: Same comprehensive tool set as all task types
        include_tools:
          - get_current_price
          - get_ticker_stats
          - get_book_ticker
          - get_klines
          - get_order_book
          - get_recent_trades
        toolkit_config:
          enable_analysis: true  # Standard: always enabled
          default_market: spot

      - class_name: FileToolkit
        enabled: true
        toolkit_config:
          enable_delete: false
          max_file_size: 10485760  # Standard: 10MB

  # Aggregator: Synthesis with Gemini Flash
  aggregator:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 5000

  # Verifier: Validation with Gemini Flash
  verifier:
    llm:
      model: openrouter/google/gemini-2.5-flash
      temperature: 0.0
      max_tokens: 3000

# Task-aware agent mapping for executor
agent_mapping:
  executors:
    # RETRIEVE: Fast data fetching with minimal reasoning
    # Use cases: "price of bitcoin", "get market cap", "fetch token holders"
    RETRIEVE:
      llm:
        model: openrouter/google/gemini-2.5-flash  # Fast & cheap for simple queries
        temperature: 0.0  # Deterministic data retrieval
        max_tokens: 4000  # Sufficient for data responses
      prediction_strategy: react
      agent_config:
        max_executions: 6  # Fewer iterations for simple retrievals

      # Data retrieval toolkits - HOMOGENIZED configs for cache reuse
      toolkits:
        - class_name: CoinGeckoToolkit
          enabled: true
          # HOMOGENIZED: Comprehensive standard tool set
          include_tools:
            - get_coin_price
            - get_coin_info
            - get_coins_markets
            - get_global_crypto_data
            - get_token_price_by_contract
            - search_coins_exchanges_categories
            - get_coin_market_chart
            - get_coin_ohlc
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            use_pro: true
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: BinanceToolkit
          enabled: true
          # HOMOGENIZED: Comprehensive standard tool set
          include_tools:
            - get_current_price
            - get_ticker_stats
            - get_book_ticker
            - get_klines
            - get_order_book
            - get_recent_trades
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            default_market: spot
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: DefiLlamaToolkit
          enabled: true
          # HOMOGENIZED: Comprehensive standard tool set
          include_tools:
            - get_protocols
            - get_protocol_tvl
            - get_chains
            - get_protocol_detail
            - get_chain_historical_tvl
            - get_protocol_fees
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            enable_pro_features: true
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: ArkhamToolkit
          enabled: true
          # HOMOGENIZED: Comprehensive standard tool set
          include_tools:
            - get_top_tokens
            - get_supported_chains
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: SerperToolkit
          enabled: true
          # HOMOGENIZED: Standard comprehensive tool set
          include_tools:
            - search
            - search_news
            - search_scholar
          toolkit_config:
            location: us
            language: en
            num_results: 5  # HOMOGENIZED: standard value

    # CODE_INTERPRET: Complex analysis, backtesting, calculations
    # Use cases: "backtest strategy", "analyze correlation", "calculate sharpe ratio"
    CODE_INTERPRET:
      llm:
        model: openrouter/anthropic/claude-sonnet-4.5  # Best for code generation
        temperature: 0.1  # Slightly creative for problem-solving
        max_tokens: 16000  # Large context for complex code
      prediction_strategy: react
      agent_config:
        max_executions: 15  # More iterations for debugging code

      # Code execution + data sources + file I/O - HOMOGENIZED configs
      toolkits:
        - class_name: E2BToolkit  # PRIMARY: Code execution
          enabled: true
          toolkit_config:
            timeout: 600  # HOMOGENIZED: standard value
            max_lifetime_hours: 23.5
            auto_reinitialize: true

        - class_name: FileToolkit  # Save analysis results
          enabled: true
          toolkit_config:
            enable_delete: false
            max_file_size: 10485760  # HOMOGENIZED: 10MB standard

        - class_name: CoinGeckoToolkit  # Data for analysis
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_coin_price
            - get_coin_info
            - get_coins_markets
            - get_global_crypto_data
            - get_token_price_by_contract
            - search_coins_exchanges_categories
            - get_coin_market_chart
            - get_coin_ohlc
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            use_pro: true
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: BinanceToolkit  # Trading data
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_current_price
            - get_ticker_stats
            - get_book_ticker
            - get_klines
            - get_order_book
            - get_recent_trades
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            default_market: spot
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: DefiLlamaToolkit  # DeFi metrics
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_protocols
            - get_protocol_tvl
            - get_chains
            - get_protocol_detail
            - get_chain_historical_tvl
            - get_protocol_fees
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            enable_pro_features: true
            storage_threshold_kb: 10  # Reduced threshold for faster storage

    # THINK: Deep market analysis, pattern recognition, insights
    # Use cases: "analyze market sentiment", "identify trends", "compare tokens"
    THINK:
      llm:
        model: openrouter/anthropic/claude-sonnet-4.5  # Best reasoning
        temperature: 0.2  # Balanced creativity + accuracy
        max_tokens: 16000  # Large context for complex reasoning
      prediction_strategy: react
      agent_config:
        max_executions: 12  # Multiple iterations for deep analysis

      # All data sources + web search + code execution - HOMOGENIZED configs
      toolkits:
        - class_name: E2BToolkit  # Code execution for complex analysis
          enabled: true
          toolkit_config:
            timeout: 600  # HOMOGENIZED: standard value
            max_lifetime_hours: 23.5
            auto_reinitialize: true

        - class_name: SerperToolkit  # Market sentiment & news
          enabled: true
          # HOMOGENIZED: Standard comprehensive tool set
          include_tools:
            - search
            - search_news
            - search_scholar
          toolkit_config:
            location: us
            language: en
            num_results: 5  # HOMOGENIZED: standard value

        - class_name: CoinGeckoToolkit  # Market data
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_coin_price
            - get_coin_info
            - get_coins_markets
            - get_global_crypto_data
            - get_token_price_by_contract
            - search_coins_exchanges_categories
            - get_coin_market_chart
            - get_coin_ohlc
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            use_pro: true
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: BinanceToolkit  # Trading patterns
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_current_price
            - get_ticker_stats
            - get_book_ticker
            - get_klines
            - get_order_book
            - get_recent_trades
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            default_market: spot
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: DefiLlamaToolkit  # DeFi trends
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_protocols
            - get_protocol_tvl
            - get_chains
            - get_protocol_detail
            - get_chain_historical_tvl
            - get_protocol_fees
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            enable_pro_features: true
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: ArkhamToolkit  # On-chain patterns
          enabled: true
          # HOMOGENIZED: Standard comprehensive tool set
          include_tools:
            - get_top_tokens
            - get_supported_chains
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: FileToolkit  # Save insights
          enabled: true
          toolkit_config:
            enable_delete: false
            max_file_size: 10485760  # HOMOGENIZED: 10MB standard

    # WRITE: Professional reports, summaries, documentation
    # Use cases: "write analysis report", "summarize findings", "create documentation"
    WRITE:
      llm:
        model: openrouter/anthropic/claude-sonnet-4.5  # Best writing quality
        temperature: 0.3  # More creative for engaging writing
        max_tokens: 16000  # Long-form content
      prediction_strategy: react
      agent_config:
        max_executions: 8  # Moderate iterations for refinement

      # File I/O + reference data + research - HOMOGENIZED configs
      toolkits:
        - class_name: FileToolkit  # PRIMARY: Save reports
          enabled: true
          toolkit_config:
            enable_delete: false
            max_file_size: 10485760  # HOMOGENIZED: 10MB standard

        - class_name: SerperToolkit  # Research & context
          enabled: true
          # HOMOGENIZED: Standard comprehensive tool set
          include_tools:
            - search
            - search_news
            - search_scholar
          toolkit_config:
            location: us
            language: en
            num_results: 5  # HOMOGENIZED: standard value

        - class_name: CoinGeckoToolkit  # Reference data
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_coin_price
            - get_coin_info
            - get_coins_markets
            - get_global_crypto_data
            - get_token_price_by_contract
            - search_coins_exchanges_categories
            - get_coin_market_chart
            - get_coin_ohlc
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            use_pro: true
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: BinanceToolkit  # Reference data
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_current_price
            - get_ticker_stats
            - get_book_ticker
            - get_klines
            - get_order_book
            - get_recent_trades
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            default_market: spot
            storage_threshold_kb: 10  # Reduced threshold for faster storage

        - class_name: DefiLlamaToolkit  # Reference data
          enabled: true
          # HOMOGENIZED: Same comprehensive tool set as RETRIEVE
          include_tools:
            - get_protocols
            - get_protocol_tvl
            - get_chains
            - get_protocol_detail
            - get_chain_historical_tvl
            - get_protocol_fees
          toolkit_config:
            enable_analysis: true  # HOMOGENIZED: always enabled
            enable_pro_features: true
            storage_threshold_kb: 10  # Reduced threshold for faster storage

  # No default_executor needed here - agents.executor is automatically used as fallback

# Runtime configuration
runtime:
  max_depth: 6  # Deep recursion for complex analysis
  verbose: true
  enable_logging: true
  log_level: INFO
  timeout: 120

# Resilience
resilience:
  retry:
    enabled: true
    max_attempts: 5
    strategy: exponential_backoff
    base_delay: 2.0
    max_delay: 60.0

  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 120.0
    half_open_max_calls: 3

  checkpoint:
    enabled: true
    storage_path: ${oc.env:ROMA_CHECKPOINT_PATH,.checkpoints}
    max_checkpoints: 20
    max_age_hours: 48.0
    compress_checkpoints: true
    verify_integrity: true

# Storage
storage:
  base_path: ${oc.env:STORAGE_BASE_PATH,/opt/sentient}
  max_file_size: 104857600  # 100MB

  postgres:
    enabled: ${oc.env:POSTGRES_ENABLED,true}
    connection_url: ${oc.env:DATABASE_URL,postgresql+asyncpg://localhost/roma_dspy}
    pool_size: 10
    max_overflow: 20

# Observability
observability:
  mlflow:
    enabled: ${oc.env:MLFLOW_ENABLED,false}
    tracking_uri: ${oc.env:MLFLOW_TRACKING_URI,http://mlflow:5000}
    experiment_name: ROMA-Crypto-Agent-Mapped
    log_traces: true
    log_compiles: true
    log_evals: true

# Logging
logging:
  level: ${oc.env:LOG_LEVEL,INFO}
  log_dir: ${oc.env:LOG_DIR,logs}
  console_format: detailed
  file_format: json
  serialize: true
  rotation: 500 MB
  retention: 90 days
  colorize: true
  backtrace: true
  diagnose: false
