# High quality profile - Maximum accuracy and determinism
# Use low temperatures for consistent outputs

agents:
  atomizer:
    llm:
      temperature: 0.0  # Maximum determinism

  planner:
    llm:
      temperature: 0.1
      max_tokens: 5000  # More space for detailed planning

  executor:
    llm:
      temperature: 0.2

  aggregator:
    llm:
      temperature: 0.0  # Deterministic aggregation
      max_tokens: 5000

  verifier:
    llm:
      temperature: 0.0  # Deterministic verification

runtime:
  max_depth: 8  # Deeper recursion for higher quality
  enable_logging: true
  log_level: INFO

resilience:
  retry:
    enabled: true
    max_attempts: 5  # More retries for higher reliability
    strategy: exponential_backoff
    base_delay: 2.0  # Longer delays for stability
    max_delay: 30.0
  circuit_breaker:
    enabled: true
    failure_threshold: 3  # Lower threshold for quality