# Lightweight profile - Minimal resource usage
# Use smaller models and reduce token limits

agents:
  atomizer:
    llm:
      max_tokens: 500

  planner:
    llm:
      max_tokens: 1500
    agent_config:
      max_subtasks: 5  # Reduce from default 10

  executor:
    llm:
      max_tokens: 1000
    tools: []  # Remove all tools for lighter execution

  aggregator:
    llm:
      max_tokens: 2000

  verifier:
    llm:
      max_tokens: 1000

runtime:
  max_concurrency: 3  # Reduce concurrency