# Tool-ready profile - Prepares configuration for future tool implementation
# Contains optimized settings for when tools become available

agents:
  executor:
    prediction_strategy: chain_of_thought  # CoT strategy until tools are implemented
    tools: []  # Tools will be added here when implementation is ready
    agent_config:
      max_tool_calls: 10  # Pre-configured for future tool usage
    strategy_config: {}  # Strategy-specific parameters

# Extended timeout prepared for future tool operations
runtime:
  timeout: 60  # Longer timeout anticipating tool execution overhead