# Simple test profile to validate Hydra configuration

defaults:
  # Import entities (Level 1)
  - /entities/models/providers@models
  - /entities/tools/definitions@tools
  # Import all agent-type configurations (Level 2)
  # These will be available at root level
  - /agents/atomizers
  - /agents/planners
  - /agents/executors
  - /agents/aggregators
  - /agents/plan_modifiers
  - _self_

# Profile metadata
name: "SimpleProfile"
description: "Simple test profile"
version: "2.0.0"

# Agent mapping - reference imported agents that are loaded from /agents/* imports
# The agents are available directly after import, we just organize them by task type
agent_mapping:
  atomizers:
    RETRIEVE: ${agents.retrieve_atomizer}
    WRITE: ${agents.write_atomizer}
    THINK: ${agents.think_atomizer}
    CODE_INTERPRET: ${agents.code_atomizer}
    IMAGE_GENERATION: ${agents.image_atomizer}
    AGGREGATE: ${agents.aggregate_atomizer}
    
  planners:
    RETRIEVE: ${agents.retrieve_planner}
    WRITE: ${agents.write_planner}
    THINK: ${agents.think_planner}
    CODE_INTERPRET: ${agents.code_planner}
    IMAGE_GENERATION: ${agents.image_planner}
    AGGREGATE: ${agents.aggregate_planner}
    
  executors:
    RETRIEVE: ${agents.retrieve_executor}
    WRITE: ${agents.write_executor}
    THINK: ${agents.think_executor}
    CODE_INTERPRET: ${agents.code_executor}
    IMAGE_GENERATION: ${agents.image_executor}
    
  aggregators:
    RETRIEVE: ${agents.retrieve_aggregator}
    WRITE: ${agents.write_aggregator}
    THINK: ${agents.think_aggregator}
    CODE_INTERPRET: ${agents.code_aggregator}
    IMAGE_GENERATION: ${agents.image_aggregator}
    AGGREGATE: ${agents.research_aggregator}
    default: ${agents.default_aggregator}
  
  plan_modifiers:
    default: ${agents.default_plan_modifier}
    error_recovery: ${agents.error_recovery_plan_modifier}

# Basic settings
settings:
  max_depth: 3
  max_parallel_tasks: 5
  max_tasks_per_level: 10
  task_timeout: 120
  total_timeout: 600
  enable_caching: true
  cache_ttl: 1800