# Example: Agent Mapping Configuration for ROMA-DSPy
# This shows how to configure task-aware agent selection

# Agent mapping defines which agent to use for each (AgentType, TaskType) combination
agent_mapping:

  # ============================================
  # ATOMIZERS - Determine if tasks need decomposition
  # ============================================
  atomizers:
    # RETRIEVE tasks - information gathering
    RETRIEVE:
      type: ATOMIZER
      task_type: RETRIEVE
      llm:
        temperature: 0.1
        max_tokens: 1000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        complexity_threshold: 3
        check_data_sources: true

    # WRITE tasks - content creation
    WRITE:
      type: ATOMIZER
      task_type: WRITE
      llm:
        temperature: 0.1
        max_tokens: 1000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        length_threshold: 1000
        check_research_needed: true

    # THINK tasks - reasoning and analysis
    THINK:
      type: ATOMIZER
      task_type: THINK
      llm:
        temperature: 0.1
        max_tokens: 1000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        complexity_indicators:
          - multi_step_reasoning
          - comparative_analysis

    # CODE_INTERPRET tasks - code execution
    CODE_INTERPRET:
      type: ATOMIZER
      task_type: CODE_INTERPRET
      llm:
        temperature: 0.1
        max_tokens: 1000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        check_dependencies: true
        max_lines_for_atomic: 100

    # IMAGE_GENERATION tasks
    IMAGE_GENERATION:
      type: ATOMIZER
      task_type: IMAGE_GENERATION
      llm:
        temperature: 0.1
        max_tokens: 1000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        check_multi_image: true

  # ============================================
  # PLANNERS - Decompose complex tasks
  # ============================================
  planners:
    RETRIEVE:
      type: PLANNER
      task_type: RETRIEVE
      llm:
        temperature: 0.3
        max_tokens: 3000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        max_subtasks: 15
        parallel_search: true

    WRITE:
      type: PLANNER
      task_type: WRITE
      llm:
        temperature: 0.3
        max_tokens: 3000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        max_subtasks: 12
        structure_planning: true

    THINK:
      type: PLANNER
      task_type: THINK
      llm:
        temperature: 0.3
        max_tokens: 3000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        max_subtasks: 10
        step_by_step: true

    CODE_INTERPRET:
      type: PLANNER
      task_type: CODE_INTERPRET
      llm:
        temperature: 0.3
        max_tokens: 3000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        max_subtasks: 8

    IMAGE_GENERATION:
      type: PLANNER
      task_type: IMAGE_GENERATION
      llm:
        temperature: 0.3
        max_tokens: 3000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        max_subtasks: 6

  # ============================================
  # EXECUTORS - Perform atomic tasks
  # ============================================
  executors:
    RETRIEVE:
      type: EXECUTOR
      task_type: RETRIEVE
      llm:
        temperature: 0.5
      prediction_strategy: chain_of_thought
      toolkits:
        - class_name: SerperToolkit
          enabled: true
          toolkit_config:
            max_results: 10
      enabled: true
      agent_config:
        max_executions: 5
        deduplicate: true

    WRITE:
      type: EXECUTOR
      task_type: WRITE
      llm:
        temperature: 0.7
        max_tokens: 4000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        output_format: markdown
        include_citations: true

    THINK:
      type: EXECUTOR
      task_type: THINK
      llm:
        temperature: 0.5
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        chain_of_thought: true
        include_confidence: true

    CODE_INTERPRET:
      type: EXECUTOR
      task_type: CODE_INTERPRET
      llm:
        temperature: 0.5
      prediction_strategy: react
      toolkits:
        - class_name: E2BToolkit
          enabled: true
          toolkit_config:
            languages: [python, javascript]
      enabled: true
      agent_config:
        safety_checks: true

    IMAGE_GENERATION:
      type: EXECUTOR
      task_type: IMAGE_GENERATION
      llm:
        temperature: 0.5
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        quality: hd

  # ============================================
  # AGGREGATORS - Combine results
  # ============================================
  aggregators:
    RETRIEVE:
      type: AGGREGATOR
      task_type: RETRIEVE
      llm:
        temperature: 0.2
        max_tokens: 4000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        synthesis_strategy: hierarchical
        deduplicate_sources: true

    WRITE:
      type: AGGREGATOR
      task_type: WRITE
      llm:
        temperature: 0.2
        max_tokens: 5000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        synthesis_strategy: narrative
        maintain_style: true

    THINK:
      type: AGGREGATOR
      task_type: THINK
      llm:
        temperature: 0.2
        max_tokens: 4000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        synthesis_strategy: logical

    CODE_INTERPRET:
      type: AGGREGATOR
      task_type: CODE_INTERPRET
      llm:
        temperature: 0.2
        max_tokens: 4000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        synthesis_strategy: modular

    IMAGE_GENERATION:
      type: AGGREGATOR
      task_type: IMAGE_GENERATION
      llm:
        temperature: 0.2
        max_tokens: 4000
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        synthesis_strategy: composite

  # ============================================
  # VERIFIERS - Validate results
  # ============================================
  verifiers:
    RETRIEVE:
      type: VERIFIER
      task_type: RETRIEVE
      llm:
        temperature: 0.1
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        verification_depth: moderate
        check_sources: true

    WRITE:
      type: VERIFIER
      task_type: WRITE
      llm:
        temperature: 0.1
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        verification_depth: moderate
        check_citations: true

    THINK:
      type: VERIFIER
      task_type: THINK
      llm:
        temperature: 0.1
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        verification_depth: deep
        check_logic: true

    CODE_INTERPRET:
      type: VERIFIER
      task_type: CODE_INTERPRET
      llm:
        temperature: 0.1
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        verification_depth: deep
        run_tests: true

    IMAGE_GENERATION:
      type: VERIFIER
      task_type: IMAGE_GENERATION
      llm:
        temperature: 0.1
      prediction_strategy: chain_of_thought
      enabled: true
      agent_config:
        verification_depth: moderate

  # ============================================
  # DEFAULT AGENTS (fallback when task_type is None or not found)
  # ============================================
  default_atomizer:
    type: ATOMIZER
    task_type: null
    llm:
      temperature: 0.1
      max_tokens: 1000
    prediction_strategy: chain_of_thought
    enabled: true
    agent_config:
      confidence_threshold: 0.8

  default_planner:
    type: PLANNER
    task_type: null
    llm:
      temperature: 0.3
      max_tokens: 3000
    prediction_strategy: chain_of_thought
    enabled: true
    agent_config:
      max_subtasks: 10

  default_executor:
    type: EXECUTOR
    task_type: null
    llm:
      temperature: 0.5
    prediction_strategy: chain_of_thought
    enabled: true
    agent_config:
      max_executions: 5

  default_aggregator:
    type: AGGREGATOR
    task_type: null
    llm:
      temperature: 0.2
      max_tokens: 4000
    prediction_strategy: chain_of_thought
    enabled: true
    agent_config:
      synthesis_strategy: hierarchical

  default_verifier:
    type: VERIFIER
    task_type: null
    llm:
      temperature: 0.1
    prediction_strategy: chain_of_thought
    enabled: true
    agent_config:
      verification_depth: moderate

# Runtime configuration
runtime:
  max_depth: 5
  enable_logging: true
  log_level: INFO
  cache_dir: .cache/dspy
